version: 2

updates:
  - directory: /action
    open-pull-requests-limit: 5
    package-ecosystem: npm
    rebase-strategy: auto
    commit-message:
      include: scope
      prefix: build
      prefix-development: chore
    schedule:
      interval: daily
